CREATE TABLE tb_alunos (
ID_ALUNO INT PRIMARY KEY IDENTITY NOT NULL,
NOME VARCHAR(150) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
SEXO CHAR(1) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL);

CREATE TABLE Situacao (
ID_SITUACAO INT PRIMARY KEY IDENTITY,
SITUACAO VARCHAR(25) NOT NULL,
DATA_CADASTRO DATETIME,
LOGIN_CADASTRO VARCHAR(15));

CREATE TABLE tb_curso (
ID_CURSO INT PRIMARY KEY IDENTITY,
NOME_CURSO VARCHAR(200) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL);

CREATE TABLE tb_turmas (
ID_TURMA INT PRIMARY KEY IDENTITY,
ID_ALUNO INT NOT NULL,
ID_CURSO INT NOT NULL,
VALOR_TURMA NUMERIC(15,2) NOT NULL,
DESCONTO NUMERIC(3,2) NOT NULL,
DATA_INICIO DATE NOT NULL,
DATA_TERMINO DATE NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15));

