CREATE TABLE tb_alunos (
ID_ALUNO INT PRIMARY KEY IDENTITY NOT NULL,
NOME VARCHAR(150) NOT NULL,
DATA_NASCIMENTO DATE NOT NULL,
SEXO CHAR(1) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL);

