CREATE DATABASE SQL_DB_CURSOSQL;

USE SQL_DB_CURSOSQL;

CREATE TABLE Cursos (
ID_CURSO NUMERIC(5) NOT NULL,
NOME_CURSO VARCHAR(100) NOT NULL,
DATA_CADASTRO DATE NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL,
DATA_ALTERACAO DATE,
LOGIN_ALTERACAO VARCHAR(15));