USE Primeiro_Banco;

CREATE TABLE Client (
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
NAME VARCHAR(255) NOT NULL,
ADDRESS VARCHAR(255) NOT NULL,
TELEPHONE VARCHAR(10) NOT NULL,
BIRTHDAY DATE NOT NULL);

INSERT INTO Client(NAME, ADDRESS, TELEPHONE, BIRTHDAY) VALUES ('João Victor', 'Rua Cristiano Machado - 661, 201 frente', '2197371121', '2000-03-16');

SELECT * FROM Client;