CREATE DATABASE DB_VAMOSPRATICAR;

USE DB_VAMOSPRATICAR;

CREATE TABLE tb_clientes(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
nome VARCHAR(100) NOT NULL,
endereco VARCHAR(150) NOT NULL,
telefone VARCHAR(15) NOT NULL,);

CREATE TABLE tb_pedidos(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_cliente INT NOT NULL,
data_pedido DATE NOT NULL,
valor FLOAT NOT NULL,
FOREIGN KEY(ID_cliente) REFERENCES tb_clientes(ID));

CREATE TABLE tb_itens_produtos(
ID INT PRIMARY KEY IDENTITY(1,1) NOT NULL,
ID_pedidos INT NOT NULL,
descricao VARCHAR(100) NOT NULL,
quantidade INT NOT NULL,
preco FLOAT NOT NULL,
FOREIGN KEY(ID_pedidos) REFERENCES tb_pedidos(ID));