USE SQL_DB_CURSOSQL

ALTER TABLE tb_turmas
ADD CONSTRAINT FK_Alunos FOREIGN KEY (ID_ALUNO) REFERENCES tb_alunos (ID_ALUNO);

ALTER TABLE tb_turmas
ADD CONSTRAINT FK_Cursos FOREIGN KEY (ID_CURSO) REFERENCES tb_curso (ID_CURSO);

ALTER TABLE tb_registro_presenca
ADD CONSTRAINT FK_TurmasRP FOREIGN KEY (ID_TURMA) REFERENCES tb_turmas (ID_TURMA);

ALTER TABLE tb_registro_presenca
ADD CONSTRAINT FK_AlunosRP FOREIGN KEY (ID_ALUNO) REFERENCES tb_alunos (ID_ALUNO);

ALTER TABLE tb_registro_presenca
ADD CONSTRAINT FK_SituacaoRP FOREIGN KEY (ID_SITUACAO) REFERENCES Situacao (ID_SITUACAO);