CREATE TABLE Alunos_Turmas (
ID_TURMA INT NOT NULL,
ID_ALUNO INT NOT NULL,
VALOR NUMERIC(13,2) NOT NULL,
VALOR_DESCONTO NUMERIC(3,2) NOT NULL,
DATA_CADASTRO DATETIME NOT NULL,
LOGIN_CADASTRO VARCHAR(15) NOT NULL);

ALTER TABLE Alunos_Turmas
ADD CONSTRAINT FK_Turma FOREIGN KEY (ID_TURMA) REFERENCES tb_turmas(ID_TURMA);

ALTER TABLE Alunos_Turmas
ADD CONSTRAINT FK_Aluno FOREIGN KEY (ID_ALUNO) REFERENCES tb_alunos(ID_ALUNO);