INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Presença Confirmada', '10/10/2025', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Falta Justificada', '10/10/2025', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Falta Injustificada', '10/10/2025', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Atestado Médico', '10/10/2025', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Licença Médica', '10/10/2025', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Féria', '10/10/2028', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Atestado de Ocorrência', '10/10/2025', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Exame Médico', '10/10/2025', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Provação de Conhecimento', '10/10/2025', 'Teste1');
INSERT INTO DBO.Situacao (SITUACAO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Ausência', '10/10/2025', 'Teste1');

SELECT * FROM dbo.Situacao;