INSERT INTO Alunos_Turmas (ID_TURMA, ID_ALUNO, VALOR, VALOR_DESCONTO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES (1, 10, 1200, 0.1, GETDATE(), 'Teste123');
INSERT INTO Alunos_Turmas (ID_TURMA, ID_ALUNO, VALOR, VALOR_DESCONTO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES (2, 2, 1200, 0.9, GETDATE(), 'Teste123');
INSERT INTO Alunos_Turmas (ID_TURMA, ID_ALUNO, VALOR, VALOR_DESCONTO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES (3, 1, 1200, 0.6, GETDATE(), 'Teste123');
INSERT INTO Alunos_Turmas (ID_TURMA, ID_ALUNO, VALOR, VALOR_DESCONTO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES (4, 8, 1200, 0.05, GETDATE(), 'Teste123');
INSERT INTO Alunos_Turmas (ID_TURMA, ID_ALUNO, VALOR, VALOR_DESCONTO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES (5, 9, 1200, 0.2, GETDATE(), 'Teste123');

SELECT * FROM Alunos_Turmas;