INSERT INTO dbo.tb_curso (NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('SQL Server', '2025-10-10', 'SQL1');

INSERT INTO dbo.tb_curso (NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Oracle', '2025-10-10', 'ORACLE1');

INSERT INTO dbo.tb_curso (NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('MySQL', '2025-10-10', 'MYSQL1');

INSERT INTO dbo.tb_curso (NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Java', '2025-10-10', 'JAVA1');

INSERT INTO dbo.tb_curso (NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Python', '2025-10-10', 'PYTHON1');

INSERT INTO dbo.tb_curso (NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('C++', '2025-10-10', 'C++1');

INSERT INTO dbo.tb_curso (NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('C#', '2025-10-10', 'C#1');

INSERT INTO dbo.tb_curso (NOME_CURSO, DATA_CADASTRO, LOGIN_CADASTRO) VALUES ('Kotlin', '2025-10-10', 'KOTLIN1');

SELECT * FROM dbo.tb_curso;