CREATE DATABASE LojaDeRoupas;
GO

USE LojaDeRoupas;
GO

CREATE TABLE Categoria (
	CategoriaID INT PRIMARY KEY IDENTITY(1,1),
	NomeCategoria VARCHAR(255) NOT NULL
);

CREATE TABLE Produtos (
	ProdutoID INT PRIMARY KEY IDENTITY(1,1),
	NomeProduto VARCHAR(100) NOT NULL,
	Preco FLOAT NOT NULL,
	Estoque INT NOT NULL,
	CategoriaID INT NOT NULL,
	CONSTRAINT FK_Produto_Categoria FOREIGN KEY (CategoriaID)
	REFERENCES Categoria (CategoriaID)
);

CREATE TABLE Cliente (
	ClienteID INT PRIMARY KEY IDENTITY(1,1),
	NomeCliente VARCHAR(100) NOT NULL,
	Email VARCHAR(100) NOT NULL,
	Telefone VARCHAR(15) NOT NULL
);

CREATE TABLE Venda (
	VendaID INT PRIMARY KEY IDENTITY(1,1),
	DataVenda DATETIME NOT NULL,
	ClienteID INT NOT NULL,
	CONSTRAINT FK_Venda_Cliente FOREIGN KEY (ClienteID)
	REFERENCES Cliente(ClienteID)
);

CREATE TABLE ItensVenda (
	ItensVendaID INT PRIMARY KEY IDENTITY(1, 1),
	VendaID INT NOT NULL,
	ProdutoID INT NOT NULL,
	Quantidade INT NOT NULL,
	CONSTRAINT FK_ItensVenda_Venda FOREIGN KEY (VendaID)
	REFERENCES Venda(VendaID),
	CONSTRAINT FK_ItensVenda_Produto FOREIGN KEY (ProdutoID)
	REFERENCES Produtos(ProdutoID)
);